### ISSUE TITLE
I can't open MyBand.WindowsPhone project on win7

### ISSUE THREAD

**Issue by undead85** [Dahrkael/MiBand-Tracker#2]
Hi, I brought a xiaomi mi band s1 and my dear phone samsung S2 is not compatible, so I need an app for my win7 laptop with bluetooth 4.0.
When I open de sln file in vstudio community 2015 only MyBand.Shared project is loaded, the other two are unavailable. Can you help me?

**Comment by Dahrkael** [comment]
Hello,
i'm afraid this app only works on Windows10+ for desktops as its a UWP project, so no Win7 support.
Aside from that, after several new firmwares for the bands over the yearsm I'm sure the app doesn't fully work as-is right now.

**Comment by undead85** [comment]
I did my homeworks ;) 
windows phone sdk is for windows 8+
So, you could make a lot of people happy if you export your classes to a WindowsForm project.

**Comment by Dahrkael** [comment]
You can't just move the logic to a winforms project because the bluetooth API doesn't exists outside of the UWP platform (that means nothing below Windows 8) and it lacks critical stuff below Windows 10 to make it work with the band. So no, it won't work.
You can try if you don't believe me

**Comment by undead85** [comment]
You are right, thank for your reply. I have only to renew my phone u.u
